### ISSUE TITLE
Error on compiling epsic

### ISSUE THREAD

**Issue by mserylak** [straten/epsic#1]
Hi Willem,

There is an error while compiling the code. It is related to `abs()` function in sample.h (line 79). As it is C++ code you probably want to use `std::abs` to conform to C++ standard or declare `cmath` if you want to keep abs. A discussion about this here (I for one wasn't aware, I still need to learn a lot of C++): https://stackoverflow.com/questions/37038073/does-the-c-standard-require-include-math-h-to-define-the-abs-overloads

**Comment by straten** [comment]
Thanks for the bug fix, Maciej.  I've checked in the fix that you suggested.

**Comment by mserylak** [comment]
Thank you very much Willem! I am closing the issue :)

**Comment by SixByNine** [comment]
Unfortunately I think this is not correct, as the integer version of std::abs is defined in cstdlib, not cmath, so my compiler still complains that std::abs is not defined for an integer. Can you also include cstdlib somewhere?

**Comment by mserylak** [comment]
Hi Willem,

I guess you are compiling on Apple? `#include <cstdlib>` added as well. It should not complain now I think. Making pull request.
