### ISSUE TITLE
Unable to install epsic

### ISSUE THREAD

**Issue by kbya99** [straten/epsic#3]
Hi, I'm trying to install epsic for psrchive. I've tried both manually installing epsic, and through the psrchive instructions. Both routes lead to the same error.

I've attached config.log here, as well as a screenshot of the error message in terminal. Please let me know how to resolve this.

[config.log](https://github.com/straten/epsic/files/4374434/config.log)
![epsic error](https://user-images.githubusercontent.com/62541161/77411296-36f0ab00-6de2-11ea-9714-c10dfbaa5804.png)

**Comment by straten** [comment]
oops. sorry about that.  I've checked in a fix.

Cheers,
Willem

**Comment by kbya99** [comment]
Hi, thanks for the help. Everything was installed with no further problems. I'll close this issue.
